name: bsub
channels:
 - anaconda
 - conda-forge
 - defaults
dependencies:
 - python=3.9.13
 - aicsimageio=4.9.2
 - numexpr=2.8.3
 - scikit-image=0.19.2
 - scipy=0.7.2
 - libgcc-ng=9.3.0
 - tifffile=2022.8.12
