name: bsub
channels:
 - anaconda
 - conda-forge
 - defaults
dependencies:
 - libgcc-ng
 - python=3.9.13
 - aicsimageio=4.9.2
 - scikit-image=0.19.2
 - numexpr=2.8.3
 - tifffile=2022.8.12
 - scipy=1.9.3
